// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD77sFwbQnzvFiGIfeg1Edumw7CCIDx9NM',
    appId: '1:302562413542:web:2709fa862be0ab366fa427',
    messagingSenderId: '302562413542',
    projectId: 'device-streaming-893d5774',
    authDomain: 'device-streaming-893d5774.firebaseapp.com',
    storageBucket: 'device-streaming-893d5774.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARL5RHCsxcXXAgK8IOBOZRgq9SEXc90_A',
    appId: '1:302562413542:android:4ccc905ab87104536fa427',
    messagingSenderId: '302562413542',
    projectId: 'device-streaming-893d5774',
    storageBucket: 'device-streaming-893d5774.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGvoMOMtaoZtqa_sNNHNhpZ4fgEeDmSaw',
    appId: '1:302562413542:ios:8ce8eede27c481096fa427',
    messagingSenderId: '302562413542',
    projectId: 'device-streaming-893d5774',
    storageBucket: 'device-streaming-893d5774.firebasestorage.app',
    iosBundleId: 'com.example.shoppingListAppLabtask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGvoMOMtaoZtqa_sNNHNhpZ4fgEeDmSaw',
    appId: '1:302562413542:ios:8ce8eede27c481096fa427',
    messagingSenderId: '302562413542',
    projectId: 'device-streaming-893d5774',
    storageBucket: 'device-streaming-893d5774.firebasestorage.app',
    iosBundleId: 'com.example.shoppingListAppLabtask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD77sFwbQnzvFiGIfeg1Edumw7CCIDx9NM',
    appId: '1:302562413542:web:9267025cf65b5d4f6fa427',
    messagingSenderId: '302562413542',
    projectId: 'device-streaming-893d5774',
    authDomain: 'device-streaming-893d5774.firebaseapp.com',
    storageBucket: 'device-streaming-893d5774.firebasestorage.app',
  );
}
